# Override to
# - not touch the upstream compose.full.yaml file.
# - prefix volume names, in case we someday run different rag stacks on the same host
# - pass the secrets
# - neuter the centralized logging observability stack by assigning them the metrics profile
# - telling r2r to log to json instead of centralized logging
# - safely remove the incompatible extra_hosts clause
# - fully define paths to images (security practice)

volumes:
  hatchet_certs:
    name: ${PROJECT_NAME}_hatchet_certs
  hatchet_config:
    name: ${PROJECT_NAME}_hatchet_config
  hatchet_api_key:
    name: ${PROJECT_NAME}_hatchet_api_key
  hatchet_rabbitmq_data:
    name: ${PROJECT_NAME}_hatchet_rabbitmq_data
  hatchet_rabbitmq_conf:
    name: ${PROJECT_NAME}_hatchet_rabbitmq_conf
  hatchet_postgres_data:
    name: ${PROJECT_NAME}_hatchet_postgres_data
  postgres_data:
    name: ${PROJECT_NAME}_postgres_data
  minio_data:
    name: ${PROJECT_NAME}_minio_data

services:
  postgres:
    image: docker.io/pgvector/pgvector:pg16

  minio:
    image: docker.io/minio/minio
    profiles:
      - metrics
      
  hatchet-postgres:
    image: docker.io/library/postgres:latest

  hatchet-rabbitmq:
    image: docker.io/library/rabbitmq:3-management

  hatchet-create-db:
    image: docker.io/library/postgres:latest

  hatchet-migration:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-migrate:v0.53.15

  setup-token:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-admin:v0.53.15

  fluent-bit:
    image: docker.io/fluent/fluent-bit:latest
    profiles:
      - metrics

  grafana:
    image: docker.io/grafana/grafana:latest
    profiles:
      - metrics

  victoria-logs:
    image: docker.io/victoriametrics/victoria-logs:v1.10.1-victorialogs
    profiles:
      - metrics
      
  unstructured:
    image: docker.io/ragtoriches/unst-prod:latest

  graph_clustering:
    image: docker.io/ragtoriches/cluster-prod

  r2r:
    image: docker.io/sciphiai/r2r:latest
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    extra_hosts:
      - host.docker.internal:[127.0.0.1]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  r2r-dashboard:
    image: docker.io/sciphiai/r2r-dashboard:1.0.3


