[app]

# LLM used for internal operations, like deriving conversation names
#fast_llm = "openai/gpt-4.1-mini"

# LLM used for user-facing output, like RAG replies
#quality_llm = "openai/gpt-4.1"

[auth]
default_admin_email="minh.haduong@gmail.com"
default_admin_password="QX9TstK7~N+TgwW"

[ingestion]
automatic_extraction = false

