[app]

# LLM used for internal operations, like deriving conversation names
#fast_llm = "openai/gpt-4.1-mini"

# LLM used for user-facing output, like RAG replies
#quality_llm = "openai/gpt-4.1"

[auth]
default_admin_email = "${R2R_ADMIN_EMAIL}"
default_admin_password = "${R2R_ADMIN_PASSWORD}"

[ingestion]
automatic_extraction = false

[agent]
tools = ["search_file_knowledge"]

[database]

  [database.graph_search_settings]
  enabled = false

[completion]
provider = "litellm"
concurrent_request_limit = 1

  [completion.generation_config]
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false
  api_base = "https://llm-tools-alpha.huma-num.fr/MH_6QCsJibvVd_jx7eTm22h3/"

[orchestration]
provider = "hatchet"
