[auth]
default_admin_email = "${R2R_ADMIN_EMAIL}"
default_admin_password = "${R2R_ADMIN_PASSWORD}"

[ingestion]
automatic_extraction = false

[database]

  [database.graph_search_settings]
  enabled = false
