name: Lint and Type Check

on:
  pull_request:
    branches: [main]  # or other protected branches
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          # Install project with dev dependencies (includes ruff, mypy, type stubs)
          pip install -e ".[dev]"

      - name: Run Ruff
        run: ruff check .

      - name: Run mypy
        run: mypy src/
